### ISSUE TITLE
ids4学习

### ISSUE THREAD

**Issue by shengshengsheng31** [jeremyjone/dotnet-study-road#1]
正在看ids4，发现大佬的宝藏文档，求更新

**Comment by jeremyjone** [comment]
> 正在看ids4，发现大佬的宝藏文档，求更新

不定期更新，有空就写哈，谢谢支持。

**Comment by shengshengsheng31** [comment]
有一个疑惑，不知大佬可否解答。
我搭建好一个identityserver服务端，建立了一个webapi项目，并且将webapi项目的接口保护起来。前端我使用vue去请求webapi，那么我是否还需要再vue中加入oidc的部分。我能否直接通过this.$http.get(‘api资源’)的方式，直接跳转到授权界面。这让我非常困惑，因为如果我还在vue中加入oidc，那么webapi中的oidc感觉有些多余了。

**Comment by jeremyjone** [comment]
@shengshengsheng31 你说的这种情况应该分成两部分：
1、前端是用户操作，自行去 is 服务器登录请求 access_token
2、后续携带该 access_token 请求 webapi，webapi 只是每次去 is 服务器验证这个 token 而已

不知道这么说，你是不是理解了。

而且你说的保护，是不是 `[Authorize]`。如果你添加了，前端不带 token 如何进行认证，不认证自然进不来。

所以，你如果使用 vue 的话，可以通过 implicit 方式进行认证，然后保存 access_token（使用 store 的话，刷新会丢失，可以重新请求），后续在请求头中加  `Authorization: Bearer xxx` 上即可，webapi 部分在管道中验证一下就可以了。并没有什么多余的。

具体你可以看一下这个 [示例代码](https://github.com/jeremyjone/dotnet-study-road/tree/master/AuthenticationAndAuthorization/Example/Jz.ApiClient) ，以及 [相关文档](https://jeremyjone.github.io/docs/document/roadmap/dotnetcore/auth/is4/intro-config.html#%E9%9A%90%E5%8C%BF%E6%A8%A1%E5%BC%8F-implicit)

网上找了张图，你可以看一下：
![image](https://user-images.githubusercontent.com/37676231/120162139-abb34680-c22a-11eb-9ebe-a6c1b660fa11.png)


当然，还有一种情况，你的 webapi 项目有自己的用户数据库，这就需要将本地用户和外部用户关联，然后按照一般方式进行即可。

**Comment by shengshengsheng31** [comment]
大佬没有写前端代码（frontend）呀，能想看看用vue怎么请求授权。我请求之后，怪怪的，并没有从Home访问并返回到Home

**Comment by jeremyjone** [comment]
@shengshengsheng31 啊哈，我看了一下，应该是提交的时候弄错了，不知道怎么文件夹变连接了。明天我重新提交一下然后 @你 哈，不好意思啦

**Comment by shengshengsheng31** [comment]
哈哈，好的，我明天关注一下，感谢感谢

**Comment by jeremyjone** [comment]
@shengshengsheng31 我更新了一下，现在有了，你可以自行测试一下，跑一下应该就清楚了。

**Comment by shengshengsheng31** [comment]
前端请求到token后，经过一段时间过期。我打算在vue的路由守卫中判断token是否过期，然后调用**signinSilent()**方法。但我发现控制台会在调用该方法后报错：**Frame window timed out**。这个报错是否有解决方案，另外想问下，我在路由守卫中判断是否是一个正常的流程。

**Comment by shengshengsheng31** [comment]
发现还有automaticSilentRenew: true，能自动刷新，唐突了
